<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: milvus.proto

namespace Milvus\Proto\Milvus;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>milvus.proto.milvus.ConnectRequest</code>
 */
class ConnectRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.milvus.proto.common.MsgBase base = 1;</code>
     */
    protected $base = null;
    /**
     * Generated from protobuf field <code>.milvus.proto.common.ClientInfo client_info = 2;</code>
     */
    protected $client_info = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Milvus\Proto\Common\MsgBase $base
     *     @type \Milvus\Proto\Common\ClientInfo $client_info
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Milvus::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.common.MsgBase base = 1;</code>
     * @return \Milvus\Proto\Common\MsgBase
     */
    public function getBase()
    {
        return $this->base;
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.common.MsgBase base = 1;</code>
     * @param \Milvus\Proto\Common\MsgBase $var
     * @return $this
     */
    public function setBase($var)
    {
        GPBUtil::checkMessage($var, \Milvus\Proto\Common\MsgBase::class);
        $this->base = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.common.ClientInfo client_info = 2;</code>
     * @return \Milvus\Proto\Common\ClientInfo
     */
    public function getClientInfo()
    {
        return $this->client_info;
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.common.ClientInfo client_info = 2;</code>
     * @param \Milvus\Proto\Common\ClientInfo $var
     * @return $this
     */
    public function setClientInfo($var)
    {
        GPBUtil::checkMessage($var, \Milvus\Proto\Common\ClientInfo::class);
        $this->client_info = $var;

        return $this;
    }

}

