<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: milvus.proto

namespace Milvus\Proto\Milvus;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>milvus.proto.milvus.GetFlushStateRequest</code>
 */
class GetFlushStateRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated int64 segmentIDs = 1;</code>
     */
    private $segmentIDs;
    /**
     * Generated from protobuf field <code>uint64 flush_ts = 2;</code>
     */
    protected $flush_ts = 0;
    /**
     * Generated from protobuf field <code>string db_name = 3;</code>
     */
    protected $db_name = '';
    /**
     * Generated from protobuf field <code>string collection_name = 4;</code>
     */
    protected $collection_name = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int[]|string[]|\Google\Protobuf\Internal\RepeatedField $segmentIDs
     *     @type int|string $flush_ts
     *     @type string $db_name
     *     @type string $collection_name
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Milvus::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated int64 segmentIDs = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSegmentIDs()
    {
        return $this->segmentIDs;
    }

    /**
     * Generated from protobuf field <code>repeated int64 segmentIDs = 1;</code>
     * @param int[]|string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSegmentIDs($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT64);
        $this->segmentIDs = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 flush_ts = 2;</code>
     * @return int|string
     */
    public function getFlushTs()
    {
        return $this->flush_ts;
    }

    /**
     * Generated from protobuf field <code>uint64 flush_ts = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setFlushTs($var)
    {
        GPBUtil::checkUint64($var);
        $this->flush_ts = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string db_name = 3;</code>
     * @return string
     */
    public function getDbName()
    {
        return $this->db_name;
    }

    /**
     * Generated from protobuf field <code>string db_name = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setDbName($var)
    {
        GPBUtil::checkString($var, True);
        $this->db_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string collection_name = 4;</code>
     * @return string
     */
    public function getCollectionName()
    {
        return $this->collection_name;
    }

    /**
     * Generated from protobuf field <code>string collection_name = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setCollectionName($var)
    {
        GPBUtil::checkString($var, True);
        $this->collection_name = $var;

        return $this;
    }

}

