<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: milvus.proto

namespace Milvus\Proto\Milvus;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>milvus.proto.milvus.GrantEntity</code>
 */
class GrantEntity extends \Google\Protobuf\Internal\Message
{
    /**
     * role
     *
     * Generated from protobuf field <code>.milvus.proto.milvus.RoleEntity role = 1;</code>
     */
    protected $role = null;
    /**
     * object
     *
     * Generated from protobuf field <code>.milvus.proto.milvus.ObjectEntity object = 2;</code>
     */
    protected $object = null;
    /**
     * object name
     *
     * Generated from protobuf field <code>string object_name = 3;</code>
     */
    protected $object_name = '';
    /**
     * privilege
     *
     * Generated from protobuf field <code>.milvus.proto.milvus.GrantorEntity grantor = 4;</code>
     */
    protected $grantor = null;
    /**
     * db name
     *
     * Generated from protobuf field <code>string db_name = 5;</code>
     */
    protected $db_name = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Milvus\Proto\Milvus\RoleEntity $role
     *           role
     *     @type \Milvus\Proto\Milvus\ObjectEntity $object
     *           object
     *     @type string $object_name
     *           object name
     *     @type \Milvus\Proto\Milvus\GrantorEntity $grantor
     *           privilege
     *     @type string $db_name
     *           db name
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Milvus::initOnce();
        parent::__construct($data);
    }

    /**
     * role
     *
     * Generated from protobuf field <code>.milvus.proto.milvus.RoleEntity role = 1;</code>
     * @return \Milvus\Proto\Milvus\RoleEntity
     */
    public function getRole()
    {
        return $this->role;
    }

    /**
     * role
     *
     * Generated from protobuf field <code>.milvus.proto.milvus.RoleEntity role = 1;</code>
     * @param \Milvus\Proto\Milvus\RoleEntity $var
     * @return $this
     */
    public function setRole($var)
    {
        GPBUtil::checkMessage($var, \Milvus\Proto\Milvus\RoleEntity::class);
        $this->role = $var;

        return $this;
    }

    /**
     * object
     *
     * Generated from protobuf field <code>.milvus.proto.milvus.ObjectEntity object = 2;</code>
     * @return \Milvus\Proto\Milvus\ObjectEntity
     */
    public function getObject()
    {
        return $this->object;
    }

    /**
     * object
     *
     * Generated from protobuf field <code>.milvus.proto.milvus.ObjectEntity object = 2;</code>
     * @param \Milvus\Proto\Milvus\ObjectEntity $var
     * @return $this
     */
    public function setObject($var)
    {
        GPBUtil::checkMessage($var, \Milvus\Proto\Milvus\ObjectEntity::class);
        $this->object = $var;

        return $this;
    }

    /**
     * object name
     *
     * Generated from protobuf field <code>string object_name = 3;</code>
     * @return string
     */
    public function getObjectName()
    {
        return $this->object_name;
    }

    /**
     * object name
     *
     * Generated from protobuf field <code>string object_name = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setObjectName($var)
    {
        GPBUtil::checkString($var, True);
        $this->object_name = $var;

        return $this;
    }

    /**
     * privilege
     *
     * Generated from protobuf field <code>.milvus.proto.milvus.GrantorEntity grantor = 4;</code>
     * @return \Milvus\Proto\Milvus\GrantorEntity
     */
    public function getGrantor()
    {
        return $this->grantor;
    }

    /**
     * privilege
     *
     * Generated from protobuf field <code>.milvus.proto.milvus.GrantorEntity grantor = 4;</code>
     * @param \Milvus\Proto\Milvus\GrantorEntity $var
     * @return $this
     */
    public function setGrantor($var)
    {
        GPBUtil::checkMessage($var, \Milvus\Proto\Milvus\GrantorEntity::class);
        $this->grantor = $var;

        return $this;
    }

    /**
     * db name
     *
     * Generated from protobuf field <code>string db_name = 5;</code>
     * @return string
     */
    public function getDbName()
    {
        return $this->db_name;
    }

    /**
     * db name
     *
     * Generated from protobuf field <code>string db_name = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setDbName($var)
    {
        GPBUtil::checkString($var, True);
        $this->db_name = $var;

        return $this;
    }

}

