<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: milvus.proto

namespace Milvus\Proto\Milvus;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>milvus.proto.milvus.ListImportTasksRequest</code>
 */
class ListImportTasksRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * target collection, list all tasks if the name is empty
     *
     * Generated from protobuf field <code>string collection_name = 1;</code>
     */
    protected $collection_name = '';
    /**
     * maximum number of tasks returned, list all tasks if the value is 0
     *
     * Generated from protobuf field <code>int64 limit = 2;</code>
     */
    protected $limit = 0;
    /**
     * Generated from protobuf field <code>string db_name = 3;</code>
     */
    protected $db_name = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $collection_name
     *           target collection, list all tasks if the name is empty
     *     @type int|string $limit
     *           maximum number of tasks returned, list all tasks if the value is 0
     *     @type string $db_name
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Milvus::initOnce();
        parent::__construct($data);
    }

    /**
     * target collection, list all tasks if the name is empty
     *
     * Generated from protobuf field <code>string collection_name = 1;</code>
     * @return string
     */
    public function getCollectionName()
    {
        return $this->collection_name;
    }

    /**
     * target collection, list all tasks if the name is empty
     *
     * Generated from protobuf field <code>string collection_name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setCollectionName($var)
    {
        GPBUtil::checkString($var, True);
        $this->collection_name = $var;

        return $this;
    }

    /**
     * maximum number of tasks returned, list all tasks if the value is 0
     *
     * Generated from protobuf field <code>int64 limit = 2;</code>
     * @return int|string
     */
    public function getLimit()
    {
        return $this->limit;
    }

    /**
     * maximum number of tasks returned, list all tasks if the value is 0
     *
     * Generated from protobuf field <code>int64 limit = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setLimit($var)
    {
        GPBUtil::checkInt64($var);
        $this->limit = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string db_name = 3;</code>
     * @return string
     */
    public function getDbName()
    {
        return $this->db_name;
    }

    /**
     * Generated from protobuf field <code>string db_name = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setDbName($var)
    {
        GPBUtil::checkString($var, True);
        $this->db_name = $var;

        return $this;
    }

}

