<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: milvus.proto

namespace Milvus\Proto\Milvus;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>milvus.proto.milvus.ReplicateMessageRequest</code>
 */
class ReplicateMessageRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.milvus.proto.common.MsgBase base = 1;</code>
     */
    protected $base = null;
    /**
     * Generated from protobuf field <code>string channel_name = 2;</code>
     */
    protected $channel_name = '';
    /**
     * Generated from protobuf field <code>uint64 BeginTs = 3;</code>
     */
    protected $BeginTs = 0;
    /**
     * Generated from protobuf field <code>uint64 EndTs = 4;</code>
     */
    protected $EndTs = 0;
    /**
     * Generated from protobuf field <code>repeated bytes Msgs = 5;</code>
     */
    private $Msgs;
    /**
     * Generated from protobuf field <code>repeated .milvus.proto.msg.MsgPosition StartPositions = 6;</code>
     */
    private $StartPositions;
    /**
     * Generated from protobuf field <code>repeated .milvus.proto.msg.MsgPosition EndPositions = 7;</code>
     */
    private $EndPositions;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Milvus\Proto\Common\MsgBase $base
     *     @type string $channel_name
     *     @type int|string $BeginTs
     *     @type int|string $EndTs
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $Msgs
     *     @type \Milvus\Proto\Msg\MsgPosition[]|\Google\Protobuf\Internal\RepeatedField $StartPositions
     *     @type \Milvus\Proto\Msg\MsgPosition[]|\Google\Protobuf\Internal\RepeatedField $EndPositions
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Milvus::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.common.MsgBase base = 1;</code>
     * @return \Milvus\Proto\Common\MsgBase
     */
    public function getBase()
    {
        return $this->base;
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.common.MsgBase base = 1;</code>
     * @param \Milvus\Proto\Common\MsgBase $var
     * @return $this
     */
    public function setBase($var)
    {
        GPBUtil::checkMessage($var, \Milvus\Proto\Common\MsgBase::class);
        $this->base = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string channel_name = 2;</code>
     * @return string
     */
    public function getChannelName()
    {
        return $this->channel_name;
    }

    /**
     * Generated from protobuf field <code>string channel_name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setChannelName($var)
    {
        GPBUtil::checkString($var, True);
        $this->channel_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 BeginTs = 3;</code>
     * @return int|string
     */
    public function getBeginTs()
    {
        return $this->BeginTs;
    }

    /**
     * Generated from protobuf field <code>uint64 BeginTs = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setBeginTs($var)
    {
        GPBUtil::checkUint64($var);
        $this->BeginTs = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 EndTs = 4;</code>
     * @return int|string
     */
    public function getEndTs()
    {
        return $this->EndTs;
    }

    /**
     * Generated from protobuf field <code>uint64 EndTs = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setEndTs($var)
    {
        GPBUtil::checkUint64($var);
        $this->EndTs = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated bytes Msgs = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getMsgs()
    {
        return $this->Msgs;
    }

    /**
     * Generated from protobuf field <code>repeated bytes Msgs = 5;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setMsgs($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::BYTES);
        $this->Msgs = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .milvus.proto.msg.MsgPosition StartPositions = 6;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getStartPositions()
    {
        return $this->StartPositions;
    }

    /**
     * Generated from protobuf field <code>repeated .milvus.proto.msg.MsgPosition StartPositions = 6;</code>
     * @param \Milvus\Proto\Msg\MsgPosition[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setStartPositions($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Milvus\Proto\Msg\MsgPosition::class);
        $this->StartPositions = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .milvus.proto.msg.MsgPosition EndPositions = 7;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getEndPositions()
    {
        return $this->EndPositions;
    }

    /**
     * Generated from protobuf field <code>repeated .milvus.proto.msg.MsgPosition EndPositions = 7;</code>
     * @param \Milvus\Proto\Msg\MsgPosition[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setEndPositions($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Milvus\Proto\Msg\MsgPosition::class);
        $this->EndPositions = $arr;

        return $this;
    }

}

