<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: milvus.proto

namespace Milvus\Proto\Milvus;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>milvus.proto.milvus.SearchRequest</code>
 */
class SearchRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * must
     *
     * Generated from protobuf field <code>.milvus.proto.common.MsgBase base = 1;</code>
     */
    protected $base = null;
    /**
     * Generated from protobuf field <code>string db_name = 2;</code>
     */
    protected $db_name = '';
    /**
     * must
     *
     * Generated from protobuf field <code>string collection_name = 3;</code>
     */
    protected $collection_name = '';
    /**
     * must
     *
     * Generated from protobuf field <code>repeated string partition_names = 4;</code>
     */
    private $partition_names;
    /**
     * must
     *
     * Generated from protobuf field <code>string dsl = 5;</code>
     */
    protected $dsl = '';
    /**
     * serialized `PlaceholderGroup`
     *
     * Generated from protobuf field <code>bytes placeholder_group = 6;</code>
     */
    protected $placeholder_group = '';
    /**
     * must
     *
     * Generated from protobuf field <code>.milvus.proto.common.DslType dsl_type = 7;</code>
     */
    protected $dsl_type = 0;
    /**
     * Generated from protobuf field <code>repeated string output_fields = 8;</code>
     */
    private $output_fields;
    /**
     * must
     *
     * Generated from protobuf field <code>repeated .milvus.proto.common.KeyValuePair search_params = 9;</code>
     */
    private $search_params;
    /**
     * Generated from protobuf field <code>uint64 travel_timestamp = 10;</code>
     */
    protected $travel_timestamp = 0;
    /**
     * guarantee_timestamp
     *
     * Generated from protobuf field <code>uint64 guarantee_timestamp = 11;</code>
     */
    protected $guarantee_timestamp = 0;
    /**
     * Generated from protobuf field <code>int64 nq = 12;</code>
     */
    protected $nq = 0;
    /**
     * Generated from protobuf field <code>bool not_return_all_meta = 13;</code>
     */
    protected $not_return_all_meta = false;
    /**
     * Generated from protobuf field <code>.milvus.proto.common.ConsistencyLevel consistency_level = 14;</code>
     */
    protected $consistency_level = 0;
    /**
     * Generated from protobuf field <code>bool use_default_consistency = 15;</code>
     */
    protected $use_default_consistency = false;
    /**
     * Generated from protobuf field <code>bool search_by_primary_keys = 16;</code>
     */
    protected $search_by_primary_keys = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Milvus\Proto\Common\MsgBase $base
     *           must
     *     @type string $db_name
     *     @type string $collection_name
     *           must
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $partition_names
     *           must
     *     @type string $dsl
     *           must
     *     @type string $placeholder_group
     *           serialized `PlaceholderGroup`
     *     @type int $dsl_type
     *           must
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $output_fields
     *     @type \Milvus\Proto\Common\KeyValuePair[]|\Google\Protobuf\Internal\RepeatedField $search_params
     *           must
     *     @type int|string $travel_timestamp
     *     @type int|string $guarantee_timestamp
     *           guarantee_timestamp
     *     @type int|string $nq
     *     @type bool $not_return_all_meta
     *     @type int $consistency_level
     *     @type bool $use_default_consistency
     *     @type bool $search_by_primary_keys
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Milvus::initOnce();
        parent::__construct($data);
    }

    /**
     * must
     *
     * Generated from protobuf field <code>.milvus.proto.common.MsgBase base = 1;</code>
     * @return \Milvus\Proto\Common\MsgBase
     */
    public function getBase()
    {
        return $this->base;
    }

    /**
     * must
     *
     * Generated from protobuf field <code>.milvus.proto.common.MsgBase base = 1;</code>
     * @param \Milvus\Proto\Common\MsgBase $var
     * @return $this
     */
    public function setBase($var)
    {
        GPBUtil::checkMessage($var, \Milvus\Proto\Common\MsgBase::class);
        $this->base = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string db_name = 2;</code>
     * @return string
     */
    public function getDbName()
    {
        return $this->db_name;
    }

    /**
     * Generated from protobuf field <code>string db_name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setDbName($var)
    {
        GPBUtil::checkString($var, True);
        $this->db_name = $var;

        return $this;
    }

    /**
     * must
     *
     * Generated from protobuf field <code>string collection_name = 3;</code>
     * @return string
     */
    public function getCollectionName()
    {
        return $this->collection_name;
    }

    /**
     * must
     *
     * Generated from protobuf field <code>string collection_name = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setCollectionName($var)
    {
        GPBUtil::checkString($var, True);
        $this->collection_name = $var;

        return $this;
    }

    /**
     * must
     *
     * Generated from protobuf field <code>repeated string partition_names = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPartitionNames()
    {
        return $this->partition_names;
    }

    /**
     * must
     *
     * Generated from protobuf field <code>repeated string partition_names = 4;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPartitionNames($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->partition_names = $arr;

        return $this;
    }

    /**
     * must
     *
     * Generated from protobuf field <code>string dsl = 5;</code>
     * @return string
     */
    public function getDsl()
    {
        return $this->dsl;
    }

    /**
     * must
     *
     * Generated from protobuf field <code>string dsl = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setDsl($var)
    {
        GPBUtil::checkString($var, True);
        $this->dsl = $var;

        return $this;
    }

    /**
     * serialized `PlaceholderGroup`
     *
     * Generated from protobuf field <code>bytes placeholder_group = 6;</code>
     * @return string
     */
    public function getPlaceholderGroup()
    {
        return $this->placeholder_group;
    }

    /**
     * serialized `PlaceholderGroup`
     *
     * Generated from protobuf field <code>bytes placeholder_group = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setPlaceholderGroup($var)
    {
        GPBUtil::checkString($var, False);
        $this->placeholder_group = $var;

        return $this;
    }

    /**
     * must
     *
     * Generated from protobuf field <code>.milvus.proto.common.DslType dsl_type = 7;</code>
     * @return int
     */
    public function getDslType()
    {
        return $this->dsl_type;
    }

    /**
     * must
     *
     * Generated from protobuf field <code>.milvus.proto.common.DslType dsl_type = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setDslType($var)
    {
        GPBUtil::checkEnum($var, \Milvus\Proto\Common\DslType::class);
        $this->dsl_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string output_fields = 8;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getOutputFields()
    {
        return $this->output_fields;
    }

    /**
     * Generated from protobuf field <code>repeated string output_fields = 8;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setOutputFields($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->output_fields = $arr;

        return $this;
    }

    /**
     * must
     *
     * Generated from protobuf field <code>repeated .milvus.proto.common.KeyValuePair search_params = 9;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSearchParams()
    {
        return $this->search_params;
    }

    /**
     * must
     *
     * Generated from protobuf field <code>repeated .milvus.proto.common.KeyValuePair search_params = 9;</code>
     * @param \Milvus\Proto\Common\KeyValuePair[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSearchParams($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Milvus\Proto\Common\KeyValuePair::class);
        $this->search_params = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 travel_timestamp = 10;</code>
     * @return int|string
     */
    public function getTravelTimestamp()
    {
        return $this->travel_timestamp;
    }

    /**
     * Generated from protobuf field <code>uint64 travel_timestamp = 10;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTravelTimestamp($var)
    {
        GPBUtil::checkUint64($var);
        $this->travel_timestamp = $var;

        return $this;
    }

    /**
     * guarantee_timestamp
     *
     * Generated from protobuf field <code>uint64 guarantee_timestamp = 11;</code>
     * @return int|string
     */
    public function getGuaranteeTimestamp()
    {
        return $this->guarantee_timestamp;
    }

    /**
     * guarantee_timestamp
     *
     * Generated from protobuf field <code>uint64 guarantee_timestamp = 11;</code>
     * @param int|string $var
     * @return $this
     */
    public function setGuaranteeTimestamp($var)
    {
        GPBUtil::checkUint64($var);
        $this->guarantee_timestamp = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 nq = 12;</code>
     * @return int|string
     */
    public function getNq()
    {
        return $this->nq;
    }

    /**
     * Generated from protobuf field <code>int64 nq = 12;</code>
     * @param int|string $var
     * @return $this
     */
    public function setNq($var)
    {
        GPBUtil::checkInt64($var);
        $this->nq = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool not_return_all_meta = 13;</code>
     * @return bool
     */
    public function getNotReturnAllMeta()
    {
        return $this->not_return_all_meta;
    }

    /**
     * Generated from protobuf field <code>bool not_return_all_meta = 13;</code>
     * @param bool $var
     * @return $this
     */
    public function setNotReturnAllMeta($var)
    {
        GPBUtil::checkBool($var);
        $this->not_return_all_meta = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.common.ConsistencyLevel consistency_level = 14;</code>
     * @return int
     */
    public function getConsistencyLevel()
    {
        return $this->consistency_level;
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.common.ConsistencyLevel consistency_level = 14;</code>
     * @param int $var
     * @return $this
     */
    public function setConsistencyLevel($var)
    {
        GPBUtil::checkEnum($var, \Milvus\Proto\Common\ConsistencyLevel::class);
        $this->consistency_level = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool use_default_consistency = 15;</code>
     * @return bool
     */
    public function getUseDefaultConsistency()
    {
        return $this->use_default_consistency;
    }

    /**
     * Generated from protobuf field <code>bool use_default_consistency = 15;</code>
     * @param bool $var
     * @return $this
     */
    public function setUseDefaultConsistency($var)
    {
        GPBUtil::checkBool($var);
        $this->use_default_consistency = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool search_by_primary_keys = 16;</code>
     * @return bool
     */
    public function getSearchByPrimaryKeys()
    {
        return $this->search_by_primary_keys;
    }

    /**
     * Generated from protobuf field <code>bool search_by_primary_keys = 16;</code>
     * @param bool $var
     * @return $this
     */
    public function setSearchByPrimaryKeys($var)
    {
        GPBUtil::checkBool($var);
        $this->search_by_primary_keys = $var;

        return $this;
    }

}

