<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: schema.proto

namespace Milvus\Proto\Schema;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>milvus.proto.schema.ArrayArray</code>
 */
class ArrayArray extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .milvus.proto.schema.ScalarField data = 1;</code>
     */
    private $data;
    /**
     * Generated from protobuf field <code>.milvus.proto.schema.DataType element_type = 2;</code>
     */
    protected $element_type = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Milvus\Proto\Schema\ScalarField[]|\Google\Protobuf\Internal\RepeatedField $data
     *     @type int $element_type
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Schema::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .milvus.proto.schema.ScalarField data = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getData()
    {
        return $this->data;
    }

    /**
     * Generated from protobuf field <code>repeated .milvus.proto.schema.ScalarField data = 1;</code>
     * @param \Milvus\Proto\Schema\ScalarField[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setData($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Milvus\Proto\Schema\ScalarField::class);
        $this->data = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.schema.DataType element_type = 2;</code>
     * @return int
     */
    public function getElementType()
    {
        return $this->element_type;
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.schema.DataType element_type = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setElementType($var)
    {
        GPBUtil::checkEnum($var, \Milvus\Proto\Schema\DataType::class);
        $this->element_type = $var;

        return $this;
    }

}

