<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: schema.proto

namespace Milvus\Proto\Schema;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 **
 * &#64;brief Collection schema
 *
 * Generated from protobuf message <code>milvus.proto.schema.CollectionSchema</code>
 */
class CollectionSchema extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string name = 1;</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>string description = 2;</code>
     */
    protected $description = '';
    /**
     * deprecated later, keep compatible with c++ part now
     *
     * Generated from protobuf field <code>bool autoID = 3 [deprecated = true];</code>
     */
    protected $autoID = false;
    /**
     * Generated from protobuf field <code>repeated .milvus.proto.schema.FieldSchema fields = 4;</code>
     */
    private $fields;
    /**
     * mark whether this table has the dynamic field function enabled.
     *
     * Generated from protobuf field <code>bool enable_dynamic_field = 5;</code>
     */
    protected $enable_dynamic_field = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *     @type string $description
     *     @type bool $autoID
     *           deprecated later, keep compatible with c++ part now
     *     @type \Milvus\Proto\Schema\FieldSchema[]|\Google\Protobuf\Internal\RepeatedField $fields
     *     @type bool $enable_dynamic_field
     *           mark whether this table has the dynamic field function enabled.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Schema::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string description = 2;</code>
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Generated from protobuf field <code>string description = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->description = $var;

        return $this;
    }

    /**
     * deprecated later, keep compatible with c++ part now
     *
     * Generated from protobuf field <code>bool autoID = 3 [deprecated = true];</code>
     * @return bool
     */
    public function getAutoID()
    {
        return $this->autoID;
    }

    /**
     * deprecated later, keep compatible with c++ part now
     *
     * Generated from protobuf field <code>bool autoID = 3 [deprecated = true];</code>
     * @param bool $var
     * @return $this
     */
    public function setAutoID($var)
    {
        GPBUtil::checkBool($var);
        $this->autoID = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .milvus.proto.schema.FieldSchema fields = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getFields()
    {
        return $this->fields;
    }

    /**
     * Generated from protobuf field <code>repeated .milvus.proto.schema.FieldSchema fields = 4;</code>
     * @param \Milvus\Proto\Schema\FieldSchema[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setFields($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Milvus\Proto\Schema\FieldSchema::class);
        $this->fields = $arr;

        return $this;
    }

    /**
     * mark whether this table has the dynamic field function enabled.
     *
     * Generated from protobuf field <code>bool enable_dynamic_field = 5;</code>
     * @return bool
     */
    public function getEnableDynamicField()
    {
        return $this->enable_dynamic_field;
    }

    /**
     * mark whether this table has the dynamic field function enabled.
     *
     * Generated from protobuf field <code>bool enable_dynamic_field = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setEnableDynamicField($var)
    {
        GPBUtil::checkBool($var);
        $this->enable_dynamic_field = $var;

        return $this;
    }

}

