<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: schema.proto

namespace Milvus\Proto\Schema;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>milvus.proto.schema.ValueField</code>
 */
class ValueField extends \Google\Protobuf\Internal\Message
{
    protected $data;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $bool_data
     *     @type int $int_data
     *     @type int|string $long_data
     *     @type float $float_data
     *     @type float $double_data
     *     @type string $string_data
     *     @type string $bytes_data
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Schema::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool bool_data = 1;</code>
     * @return bool
     */
    public function getBoolData()
    {
        return $this->readOneof(1);
    }

    /**
     * Generated from protobuf field <code>bool bool_data = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setBoolData($var)
    {
        GPBUtil::checkBool($var);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 int_data = 2;</code>
     * @return int
     */
    public function getIntData()
    {
        return $this->readOneof(2);
    }

    /**
     * Generated from protobuf field <code>int32 int_data = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setIntData($var)
    {
        GPBUtil::checkInt32($var);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 long_data = 3;</code>
     * @return int|string
     */
    public function getLongData()
    {
        return $this->readOneof(3);
    }

    /**
     * Generated from protobuf field <code>int64 long_data = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setLongData($var)
    {
        GPBUtil::checkInt64($var);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>float float_data = 4;</code>
     * @return float
     */
    public function getFloatData()
    {
        return $this->readOneof(4);
    }

    /**
     * Generated from protobuf field <code>float float_data = 4;</code>
     * @param float $var
     * @return $this
     */
    public function setFloatData($var)
    {
        GPBUtil::checkFloat($var);
        $this->writeOneof(4, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>double double_data = 5;</code>
     * @return float
     */
    public function getDoubleData()
    {
        return $this->readOneof(5);
    }

    /**
     * Generated from protobuf field <code>double double_data = 5;</code>
     * @param float $var
     * @return $this
     */
    public function setDoubleData($var)
    {
        GPBUtil::checkDouble($var);
        $this->writeOneof(5, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>string string_data = 6;</code>
     * @return string
     */
    public function getStringData()
    {
        return $this->readOneof(6);
    }

    /**
     * Generated from protobuf field <code>string string_data = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setStringData($var)
    {
        GPBUtil::checkString($var, True);
        $this->writeOneof(6, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes bytes_data = 7;</code>
     * @return string
     */
    public function getBytesData()
    {
        return $this->readOneof(7);
    }

    /**
     * Generated from protobuf field <code>bytes bytes_data = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setBytesData($var)
    {
        GPBUtil::checkString($var, False);
        $this->writeOneof(7, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getData()
    {
        return $this->whichOneof("data");
    }

}

