<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: schema.proto

namespace Milvus\Proto\Schema;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * vector field clustering info
 *
 * Generated from protobuf message <code>milvus.proto.schema.VectorClusteringInfo</code>
 */
class VectorClusteringInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * for multi vectors
     *
     * Generated from protobuf field <code>string field = 1;</code>
     */
    protected $field = '';
    /**
     * Generated from protobuf field <code>.milvus.proto.schema.VectorField centroid = 2;</code>
     */
    protected $centroid = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $field
     *           for multi vectors
     *     @type \Milvus\Proto\Schema\VectorField $centroid
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Schema::initOnce();
        parent::__construct($data);
    }

    /**
     * for multi vectors
     *
     * Generated from protobuf field <code>string field = 1;</code>
     * @return string
     */
    public function getField()
    {
        return $this->field;
    }

    /**
     * for multi vectors
     *
     * Generated from protobuf field <code>string field = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setField($var)
    {
        GPBUtil::checkString($var, True);
        $this->field = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.schema.VectorField centroid = 2;</code>
     * @return \Milvus\Proto\Schema\VectorField
     */
    public function getCentroid()
    {
        return $this->centroid;
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.schema.VectorField centroid = 2;</code>
     * @param \Milvus\Proto\Schema\VectorField $var
     * @return $this
     */
    public function setCentroid($var)
    {
        GPBUtil::checkMessage($var, \Milvus\Proto\Schema\VectorField::class);
        $this->centroid = $var;

        return $this;
    }

}

