version: '3.5'

services:
  etcd:
    container_name: php-milvus-etcd
    image: quay.io/coreos/etcd:v3.5.0
    env_file:
      - .env
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/etcd:/etcd
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd

  minio:
    container_name: php-milvus-minio
    image: minio/minio:RELEASE.2020-12-03T00-03-10Z
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    env_file:
      - .env
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/minio:/minio_data
    command: minio server /minio_data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  standalone:
    container_name: php-milvus-standalone
    image: ${IMAGE_REPO}/milvus:v2.2.12
    command: ["milvus", "run", "standalone"]
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
      DOCKER_VOLUME_DIRECTORY: ./data
    env_file:
      - .env
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/milvus:/var/lib/milvus
      - ./config/milvus.yaml:/milvus/configs/milvus.yaml
      - ./config/cert:/milvus/configs/cert
    ports:
      - "19530:19530"
    depends_on:
      - "etcd"
      - "minio"

  attu:
    container_name: php-milvus-attu
    image: zilliz/attu:v2.2.3
    ports:
      - "8000:3000"
    environment:
      - MILVUS_URL=standalone:19530

networks:
  default:
    name: milvus
