<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common.proto

namespace Milvus\Proto\Common;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>milvus.proto.common.MsgBase</code>
 */
class MsgBase extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.milvus.proto.common.MsgType msg_type = 1;</code>
     */
    protected $msg_type = 0;
    /**
     * Generated from protobuf field <code>int64 msgID = 2;</code>
     */
    protected $msgID = 0;
    /**
     * Generated from protobuf field <code>uint64 timestamp = 3;</code>
     */
    protected $timestamp = 0;
    /**
     * Generated from protobuf field <code>int64 sourceID = 4;</code>
     */
    protected $sourceID = 0;
    /**
     * Generated from protobuf field <code>int64 targetID = 5;</code>
     */
    protected $targetID = 0;
    /**
     * Generated from protobuf field <code>map<string, string> properties = 6;</code>
     */
    private $properties;
    /**
     * Generated from protobuf field <code>.milvus.proto.common.ReplicateInfo replicateInfo = 7;</code>
     */
    protected $replicateInfo = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $msg_type
     *     @type int|string $msgID
     *     @type int|string $timestamp
     *     @type int|string $sourceID
     *     @type int|string $targetID
     *     @type array|\Google\Protobuf\Internal\MapField $properties
     *     @type \Milvus\Proto\Common\ReplicateInfo $replicateInfo
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Common::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.common.MsgType msg_type = 1;</code>
     * @return int
     */
    public function getMsgType()
    {
        return $this->msg_type;
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.common.MsgType msg_type = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setMsgType($var)
    {
        GPBUtil::checkEnum($var, \Milvus\Proto\Common\MsgType::class);
        $this->msg_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 msgID = 2;</code>
     * @return int|string
     */
    public function getMsgID()
    {
        return $this->msgID;
    }

    /**
     * Generated from protobuf field <code>int64 msgID = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMsgID($var)
    {
        GPBUtil::checkInt64($var);
        $this->msgID = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 timestamp = 3;</code>
     * @return int|string
     */
    public function getTimestamp()
    {
        return $this->timestamp;
    }

    /**
     * Generated from protobuf field <code>uint64 timestamp = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTimestamp($var)
    {
        GPBUtil::checkUint64($var);
        $this->timestamp = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 sourceID = 4;</code>
     * @return int|string
     */
    public function getSourceID()
    {
        return $this->sourceID;
    }

    /**
     * Generated from protobuf field <code>int64 sourceID = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSourceID($var)
    {
        GPBUtil::checkInt64($var);
        $this->sourceID = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 targetID = 5;</code>
     * @return int|string
     */
    public function getTargetID()
    {
        return $this->targetID;
    }

    /**
     * Generated from protobuf field <code>int64 targetID = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTargetID($var)
    {
        GPBUtil::checkInt64($var);
        $this->targetID = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, string> properties = 6;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getProperties()
    {
        return $this->properties;
    }

    /**
     * Generated from protobuf field <code>map<string, string> properties = 6;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setProperties($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
        $this->properties = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.common.ReplicateInfo replicateInfo = 7;</code>
     * @return \Milvus\Proto\Common\ReplicateInfo
     */
    public function getReplicateInfo()
    {
        return $this->replicateInfo;
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.common.ReplicateInfo replicateInfo = 7;</code>
     * @param \Milvus\Proto\Common\ReplicateInfo $var
     * @return $this
     */
    public function setReplicateInfo($var)
    {
        GPBUtil::checkMessage($var, \Milvus\Proto\Common\ReplicateInfo::class);
        $this->replicateInfo = $var;

        return $this;
    }

}

