<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common.proto

namespace Milvus\Proto\Common;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>milvus.proto.common.ReplicateInfo</code>
 */
class ReplicateInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool isReplicate = 1;</code>
     */
    protected $isReplicate = false;
    /**
     * Generated from protobuf field <code>uint64 msgTimestamp = 2;</code>
     */
    protected $msgTimestamp = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $isReplicate
     *     @type int|string $msgTimestamp
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Common::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool isReplicate = 1;</code>
     * @return bool
     */
    public function getIsReplicate()
    {
        return $this->isReplicate;
    }

    /**
     * Generated from protobuf field <code>bool isReplicate = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsReplicate($var)
    {
        GPBUtil::checkBool($var);
        $this->isReplicate = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 msgTimestamp = 2;</code>
     * @return int|string
     */
    public function getMsgTimestamp()
    {
        return $this->msgTimestamp;
    }

    /**
     * Generated from protobuf field <code>uint64 msgTimestamp = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMsgTimestamp($var)
    {
        GPBUtil::checkUint64($var);
        $this->msgTimestamp = $var;

        return $this;
    }

}

