<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common.proto

namespace Milvus\Proto\Common;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>milvus.proto.common.ServerInfo</code>
 */
class ServerInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string build_tags = 1;</code>
     */
    protected $build_tags = '';
    /**
     * Generated from protobuf field <code>string build_time = 2;</code>
     */
    protected $build_time = '';
    /**
     * Generated from protobuf field <code>string git_commit = 3;</code>
     */
    protected $git_commit = '';
    /**
     * Generated from protobuf field <code>string go_version = 4;</code>
     */
    protected $go_version = '';
    /**
     * Generated from protobuf field <code>string deploy_mode = 5;</code>
     */
    protected $deploy_mode = '';
    /**
     * reserved for newly-added feature if necessary.
     *
     * Generated from protobuf field <code>map<string, string> reserved = 6;</code>
     */
    private $reserved;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $build_tags
     *     @type string $build_time
     *     @type string $git_commit
     *     @type string $go_version
     *     @type string $deploy_mode
     *     @type array|\Google\Protobuf\Internal\MapField $reserved
     *           reserved for newly-added feature if necessary.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Common::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string build_tags = 1;</code>
     * @return string
     */
    public function getBuildTags()
    {
        return $this->build_tags;
    }

    /**
     * Generated from protobuf field <code>string build_tags = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setBuildTags($var)
    {
        GPBUtil::checkString($var, True);
        $this->build_tags = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string build_time = 2;</code>
     * @return string
     */
    public function getBuildTime()
    {
        return $this->build_time;
    }

    /**
     * Generated from protobuf field <code>string build_time = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setBuildTime($var)
    {
        GPBUtil::checkString($var, True);
        $this->build_time = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string git_commit = 3;</code>
     * @return string
     */
    public function getGitCommit()
    {
        return $this->git_commit;
    }

    /**
     * Generated from protobuf field <code>string git_commit = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setGitCommit($var)
    {
        GPBUtil::checkString($var, True);
        $this->git_commit = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string go_version = 4;</code>
     * @return string
     */
    public function getGoVersion()
    {
        return $this->go_version;
    }

    /**
     * Generated from protobuf field <code>string go_version = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setGoVersion($var)
    {
        GPBUtil::checkString($var, True);
        $this->go_version = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string deploy_mode = 5;</code>
     * @return string
     */
    public function getDeployMode()
    {
        return $this->deploy_mode;
    }

    /**
     * Generated from protobuf field <code>string deploy_mode = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setDeployMode($var)
    {
        GPBUtil::checkString($var, True);
        $this->deploy_mode = $var;

        return $this;
    }

    /**
     * reserved for newly-added feature if necessary.
     *
     * Generated from protobuf field <code>map<string, string> reserved = 6;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getReserved()
    {
        return $this->reserved;
    }

    /**
     * reserved for newly-added feature if necessary.
     *
     * Generated from protobuf field <code>map<string, string> reserved = 6;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setReserved($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
        $this->reserved = $arr;

        return $this;
    }

}

