<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common.proto

namespace Milvus\Proto\Common;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>milvus.proto.common.Status</code>
 */
class Status extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.milvus.proto.common.ErrorCode error_code = 1 [deprecated = true];</code>
     */
    protected $error_code = 0;
    /**
     * Generated from protobuf field <code>string reason = 2;</code>
     */
    protected $reason = '';
    /**
     * Generated from protobuf field <code>int32 code = 3;</code>
     */
    protected $code = 0;
    /**
     * Generated from protobuf field <code>bool retriable = 4;</code>
     */
    protected $retriable = false;
    /**
     * Generated from protobuf field <code>string detail = 5;</code>
     */
    protected $detail = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $error_code
     *     @type string $reason
     *     @type int $code
     *     @type bool $retriable
     *     @type string $detail
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Common::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.common.ErrorCode error_code = 1 [deprecated = true];</code>
     * @return int
     */
    public function getErrorCode()
    {
        return $this->error_code;
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.common.ErrorCode error_code = 1 [deprecated = true];</code>
     * @param int $var
     * @return $this
     */
    public function setErrorCode($var)
    {
        GPBUtil::checkEnum($var, \Milvus\Proto\Common\ErrorCode::class);
        $this->error_code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string reason = 2;</code>
     * @return string
     */
    public function getReason()
    {
        return $this->reason;
    }

    /**
     * Generated from protobuf field <code>string reason = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setReason($var)
    {
        GPBUtil::checkString($var, True);
        $this->reason = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 code = 3;</code>
     * @return int
     */
    public function getCode()
    {
        return $this->code;
    }

    /**
     * Generated from protobuf field <code>int32 code = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setCode($var)
    {
        GPBUtil::checkInt32($var);
        $this->code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool retriable = 4;</code>
     * @return bool
     */
    public function getRetriable()
    {
        return $this->retriable;
    }

    /**
     * Generated from protobuf field <code>bool retriable = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setRetriable($var)
    {
        GPBUtil::checkBool($var);
        $this->retriable = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string detail = 5;</code>
     * @return string
     */
    public function getDetail()
    {
        return $this->detail;
    }

    /**
     * Generated from protobuf field <code>string detail = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setDetail($var)
    {
        GPBUtil::checkString($var, True);
        $this->detail = $var;

        return $this;
    }

}

